Домашняя работа_№2
Lumkooo/FocusStartHomeworks pull request #5
Opened 2020-10-24 10:31 UTC by Lumkooo

Реализован потокобезопасный массив - ThreadSafeArray и его основные методы

2020-10-26 09:31 UTC, korshunigor commented
Принято на проверку

2020-10-26 16:41 UTC, GkFoxes reviewed
Хорошая работа, как поправишь мелкие косяки, то сможешь вливать в Develop. Надо будет пингануть, чтобы первое дз проверили)

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
Здесь в файле все окей, но есть проблемы с .gitignore и .DS_Store. Попробуй сделать как на видео 

https://www.youtube.com/watch?v=N6wQ28h-MmE&list=PL5xejD2Y5yw6Xy-II4ThSmL6lCLvdV7B_&index=1

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/AppDelegate.swift
> +
Желательно удалять путые строки, я понимаю, что это эппл сгенерировал, но все равно все лишнее удалять

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/AppDelegate.swift
> +    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {
Можно удалить функцию, раз она пока не используется

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/AppDelegate.swift
> +
тоже лишние пробелы удалить

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/SceneDelegate.swift
> +
пустые строки

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/SceneDelegate.swift
> +    func sceneDidDisconnect(_ scene: UIScene) {
удалить все методы ниже и пустые строки, пока функции не используются

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ThreadSafeArray.swift
> +import Foundation
Можно удалить во всех файлах import Foundation, в Xcode проектах тут они не обязательны

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ThreadSafeArray.swift
> +                                  , attributes: .concurrent)
Не правильно перенес, запятую выше лучше оставить

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ViewController.swift
> +    override func viewDidLoad() {
Лучше отделить пустой строкой label и viewDidLoad

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ViewController.swift
> +
пустую строку удалить

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ViewController.swift
> +//        var array = Array<Int>()
Я бы написал тут комментарий, почему мы данный код комментируем. Чтобы сходу понятно было, почему тут так происходит

2020-10-26 16:41 UTC, GkFoxes commented on Homework_№2/ViewController.swift
> +        print("Количество элементов в потокобезопасном массиве: ",resultThreadSafeArray.count)
Почему бы не создать переменную и туда все перенести, уберем дублирование кода:

"Количество элементов в потокобезопасном массиве: ",resultThreadSafeArray.count)" 

В label просто будем делать примерно так someProperty + "\n(Результат так же выведен print-ом)"

2020-10-26 17:58 UTC, korshunigor requested changes

2020-10-26 17:58 UTC, korshunigor commented on Homework_№2/ThreadSafeArray.swift
> +    }
На данный момент задание не выполнено. Сейчас исключен race condition в случае, если мы одновременно в разных задачах пытаемся удалить/добавить элемент, однако, если мы одновременно в двух асинхронных задачах попытаемся вызывать удаление/добавление элементов и в другой извлечение значения (например проверку на contains), то мы поймаем race condition и с очень большой вероятностью крашнемся.

Любые обращения к threadSafeArray должны происходить с использованием изолированной очереди, причем в случае изменения значения должны применяться барьеры (с барьерами проблем нет), нужно доработать.

P.s. технически, threadSafeArray - "потокобезопасный массив" не является таковым, потому что это обычный массив, потокобезопасным будет только экземпляр ThreadSafeArray<Element: Equatable>, лучше переименовать.

2020-10-26 17:58 UTC, korshunigor commented on Homework_№2/ThreadSafeArray.swift
> +final class ThreadSafeArray<Element: Equatable> {
Из условия: "_Должен иметь возможность работать с элементами любого типа_", сейчас же мы работаем только с типами реализующими Equatable. 
Для реализации метода contains лучше воспользоваться [расширением с оговоркой where](https://swiftbook.ru/content/languageguide/generics-in-swift/#extensions-with-a-generic-where-clause)

2020-10-26 17:58 UTC, korshunigor commented on Homework_№2/ThreadSafeArray.swift
> +    let safeQueue = DispatchQueue(label: "com.Lumko.Homework--2.safeQueue"
safeQueue относится только к внутренней реализации ThreadSafeArray, лучше сделать ее приватной

2020-10-27 08:08 UTC, Lumkooo commented on Homework_№2/ThreadSafeArray.swift
> +import Foundation
Если удалить import Foundation, то выдает ошибку - Cannot find 'DispatchQueue' in scope, поэтому все же надо оставить, да?

2020-10-27 08:15 UTC, GkFoxes commented on Homework_№2/ThreadSafeArray.swift
> +import Foundation
Значит в данном файле оставлять)

2020-10-27 11:19 UTC, korshunigor approved these changes
По основному условию (организации потокобезопасности) вопросов не имею, дальнейшие правки на усмотрение Дмитрия

2020-10-27 11:22 UTC, GkFoxes approved these changes
Хорошо!

2020-10-27 11:22 UTC, GkFoxes commented on Homework_№2.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
Напоминаю, что лучше везде удалить .DS_Store

2020-11-01 04:34 UTC, merged