Домашняя работа №5
Lumkooo/FocusStartHomeworks pull request #9
Opened 2020-11-15 09:34 UTC by Lumkooo

Рефакторинг четвертой домашней работа реализован в 4 вариантах архитектур :
MVC -  Homework_№5_MVC(изначальный вариант)
MVP - Homework_№5_MVP
VIPER - Homework_№5_VIPER
CLEAN - Homework_№5_CLEAN
(Не хватило времени разобраться с MVVM, но с ним разберусь на неделе сам)

2020-11-15 13:17 UTC, noreasonwhyiamhere commented
задание принято на проверку)

2020-11-25 19:07 UTC, korshunigor commented
Что-то пошло не так, ссылка на одну версию проекта сломана
<img width="267" alt="Снимок экрана 2020-11-25 в 22 07 22" src="https://user-images.githubusercontent.com/17854702/100271497-9d7a2a00-2f6a-11eb-8cc8-fd6dcbe54a6d.png">

2020-11-25 19:08 UTC, noreasonwhyiamhere commented
> Что-то пошло не так, ссылка на одну версию проекта сломана
> <img alt="Снимок экрана 2020-11-25 в 22 07 22" width="267" src="https://user-images.githubusercontent.com/17854702/100271497-9d7a2a00-2f6a-11eb-8cc8-fd6dcbe54a6d.png">

ой я тоже это заметила(( надо починить

2020-11-25 21:32 UTC, korshunigor requested changes
Так, я пока отсмотрел только VIPER (не весь, не отсматривал модуль Detail), есть проблемы общего характера (нейминг, оформление (после двоеточий теряются пробелы и т.д.), отсмотри пожалуйста полностью весь код, где встретишь поправь их.

По архитектуре набросал основные замечания которые есть уже сейчас, попробуй поправить их и по такому же принципу переделать модуль Detail. При повторном ревью отсмотрю уже весь Viper и если замечаний будет не много, то приступлю к следующей архитектуре.

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +        let presenter: ViewToPresenterProtocol & InteractorToPresenterProtocol = MasterPresenter()
Малость перемудрил. Мы инициализируем презентер, чтобы засетить его в наш ViewController, внутрик которого презентер закрыт этими протоколами. В данном случае мы можем упростить написав:
```swift
let presenter = MasterPresenter()
```
Нам важно, чтобы презентер был закрыт соответствующим протоколом в презентуете и в интеракторе, но на этапе конфигурации это не важно, сам MasterPresenter реализует сразу оба, по этому в явном указании протоколов нет необходимости.

Более того, это позволит избавиться от необходимости добавлять в протокол router и interactor, их можно будет сделать приватными

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +        guard let viewController = (view  as? MasterView)?.findViewController() as? MasterViewController else { fatalError("Произошла ошибка!")}
Каст к MasterViewController вроде тут не нужен, потому что нам достаточно оперировать просто UIViewController

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    func showDetailViewController(on view: MasterViewPresenter, with dataModel: DataModel) {
Но ведь мы же можем внутри роутера сохранить слабую ссылку на ViewController (причем именно на базовый UIViewController, дабы мы знали только о методах навигации этого экрана), тогда нам не придется передавать сюда презентер, из презента вытаскивать VC, а из VC вытаскивать Split.

Причем сам экран можно передавать через инициализатор роутера.

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterProtocols.swift
> +protocol ViewToPresenterProtocol: class {
IMasterPresenter

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterProtocols.swift
> +protocol PresenterToInteractorProtocol: class {
IMasterInteractor

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterProtocols.swift
> +protocol InteractorToPresenterProtocol: class {
IMasterInteractorOutput

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterProtocols.swift
> +protocol PresenterToRouterProtocol: class {
IMasterRouter

2020-11-25 21:32 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +        masterController.presenter?.interactor?.presenter = presenter
Если интерактор проинициализировать в константу, а потом уже сетить эту константу, то мы сможем убрать  presenter из протокола интерактора, сделать его приватным. Сейчас получается так, что мы зная о контроллере через него можем вытащить информацию обо всем (и о презентере, и об интеракторе, и о роутере), а это не очень хорошо.

2020-11-26 07:27 UTC, korshunigor commented
Вот ДЗ №6 не надо было мержить сюда по идее... Там хоть и поставили апрув, это не означало что можно лить сюда, а лишь означало что задание выполнено и ПО МЕРЕ ВОЗМОЖНОСТИ его можно сливать в develop. 
Вливать одну задачу в другую допустимо только если бы эта ветка была рутовой для нескольких задач. Надо было подождать пока сольется в develop это ДЗ и только потом заливать ДЗ №6 напрямую в develop. А если не хочется ждать завершения ревью по предыдущему ДЗ, то все последующие надо создавать из ветки develope, чтобы можно было разрабатывать их параллельно и сливать по мере готовности.

2020-11-26 08:06 UTC, Lumkooo commented on Homework_№5/CLEAN/Homework_№4/Entities/ImagesModel.swift
> +    }
Из-за того, что в 4 ДЗ по заданию нужны были две разные картинки на одном экране, то я и сделал две картинки, которые будут повторяться на каждом экране. А dataModel сюда передавал, делая это как более реалистичное приложение, где картинки мы будем брать по полю URL/ID/Название или как-либо еще, которое было бы в dataModel, а так как в этой работе всегда показываются две картинки, то я решил не создавать в dataModel поле image(потому что они везде были бы одинаковы). Если надо будет, то могу переделать и добавить в dataModel поле image =)

2020-11-26 08:09 UTC, Lumkooo commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    func showDetailViewController(on view: MasterViewPresenter, with dataModel: DataModel) {
Здесь немного не понял =(

В Router-е создать 
weak var ui:IMasterView

И при создании Router-а передавать в инициализатор этот параметр?
Или нет?

2020-11-26 08:11 UTC, Lumkooo commented
Исправил все замечания во всех трех архитектурах( кроме замечания про MasterRouter, немного не понял)

А почему ссылка на CLEAN сломана - не знаю. Сделал git pull, все нормально было. Надеюсь сейчас все будет хорошо

2020-11-26 08:14 UTC, Lumkooo commented
А про то, что влил шестую дз - извини, не знал.

2020-11-26 11:36 UTC, korshunigor commented on Homework_№5/CLEAN/Homework_№4/Entities/ImagesModel.swift
> +    }
Но ведь по коду у нас есть 6 картинок, да и в кассетах они лежат, получается задумка была для каждой новости все же сделать свой набор картинок (да и по заданию это требовалось), ведь так? Получается надо либо это все подчистить, либо все же заюзать как задумывалось. Делать "видимость" не очень хорошо, либо мы передаем данные и их используем, либо эти данные надо выпилить из входных параметров, иначе это вводит в заблуждение тех кто в будущем может работать с этим кодом =)

2020-11-26 11:39 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    func showDetailViewController(on view: MasterViewPresenter, with dataModel: DataModel) {
скорее в роутере создать 
```swift
private weak var vc: UIViewController?
```
Добавить инициализатор:
```swift
init(vc: UIViewController) {
    self.vc = vc
}
```
Просто если есть возможность передать что-то как явную зависимость при инициализации и скрыть ее внутри как приватное свойство объекта, то лучше этой возможностью воспользоваться.

2020-11-26 11:41 UTC, korshunigor commented
> А про то, что влил шестую дз - извини, не знал.

Это не супер критично, просто отписал на всякий случай, чтобы в следующих ДЗ такой проблемы не было, не кипишуй 😊

2020-11-26 20:57 UTC, korshunigor commented
> А почему ссылка на CLEAN сломана - не знаю. Сделал git pull, все нормально было. Надеюсь сейчас все будет хорошо

Ссылка не починилась, удали пожалуйста ее из воркспейса и добавь пожалуйста заново. Локально у себя это сделал, ссылка починилась тогда, но нужно чтобы в гите тоже все ОК было )

2020-11-26 21:40 UTC, korshunigor requested changes
Основное что нужно исправить:
1) Из протоколов роутера, презентера, интерактора и вью не должны быть доступны объекты о которых они знают. Мы не должны иметь возможность через вью обращаться к презентеру, из презентера иметь доступ к интерактору и роутеру, как раз для исключения этого доступа мы закрываем каждый класс протоколом ограничивающим доступ ко всему что нам не нужно.
2) Для каждого модуля мы создаем свой собственный Assembly, а не один сразу на все модули
3) Роутер не должен конфигурировать вью (у него не должно быть методов по типу "create" возвращающих вьюху), он отвечает исключительно за переход от модуля к модулю, по этому содержит исключительно метод "show<Экран>", в котором роутер обращается к ассембли нужного экрана, конфигурирует модуль, получив контроллер (допустим UIViewController) вызывает его презентацию

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Detail/DetailInteractor.swift
> +    var presenter: IDetailInteractorOutput? { get set }
По идее он не должен торчать из протокола `IDetailInteractor`. Этот протокол нужен исключительно для получения данных из интерактора, а знание о презентуете это уже внутренняя логика самого интерактора

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Detail/DetailInteractor.swift
> +    init(dataModel:DataModel) {
Потерялся пробел после `:`

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Detail/DetailPresenter.swift
> +    var ui: IDetailView? { get set }
Знание презентера о UI это внутренняя логика презентера, давай уберем его из протокола

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Detail/DetailPresenter.swift
> +    init(interactor:IDetailInteractor, router:IDetailRouter) {
потерялись пробелы после `:`

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Detail/DetailPresenter.swift
> +        self.interactor.presenter = self
Эта установка по идее должна быть сделана в Assembly модуля, тогда и из протокола мы сможем выпилить знание о презентере

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterAssembly.swift
> +enum MasterAssembly {
Так, тут у нас произошло недопонимание похоже =)

`Assembly` создается для каждого модуля в отдельности, то есть на выходе у нас должно получиться 3 объекта:
1) MasterAssembly
2) DetailAssembly
3) SplitAssembly

В каждом из объектов всего по 1 статичному методу отвечающему за конфигурирование модуля:
```swift
static func createModule() -> <Тип контроллера, например UIViewController>
```

В этот же метод могут перековаться зависимости (если в них есть необходимость)

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterAssembly.swift
> +    static func showDetailViewController(on view: IMasterView, with dataModel: DataModel) {
Assembly не должен содержать методы вроде `show`, `push` и т.д., он не отвечает за переходы и за презентацию модуля, ассембли отвечает исключительно за конфигурацию модуля, а презентация должна происходить уже в роутере.

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterInteractor.swift
> +    var presenter: IMasterInteractorOutput? { get set }
Не должен присутствовать в протоколе

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterPresenter.swift
> +import Foundation
Вроде можно удалить

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterPresenter.swift
> +    var ui: IMasterView? { get set }
Не должен присутствовать в протокле

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterPresenter.swift
> +    func selectCellAt(index:Int)
Потерялись пробелы после двоеточий

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterPresenter.swift
> +            fatalError("Somethingn is wrong")
И все же думаю тут можно не фаталить приложение, а обойтись тем что мы сделаем ранний выход, а вместо fatalError бросить ассерт, в конце концов в других методах (например в методе выше) мы спокойно обращаемся к опциональному ui не краша приложение, то есть "морально готовы к тому что его может не быть и ни чего не выполнится"

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    static func createSplitViewController() -> UISplitViewController
Этих методов не должно быть в роутере, за "create" отвечают Assembly, причем для каждого модуля свой. Роутер (и его протокол соответственно) должен содержать исключительно методы перехода (например showDetailViewController)

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    func showDetailViewController(on view: IMasterView, with dataModel: DataModel)
В роутере можно сохранить ссылку на экран, тогда нам не надо будет передавать его в этот метод.
```swift
class MasterRouter {
    private weak var vc: UIViewCintriller?

    init(vc: UIViewController) {
        self.vc = vc
    }
}

extension MasterRouter: IMasterRoute {
    func showDetailViewController(dataModel: DataModel) {
        let nextVC = DetailAssembly.createModule(with: dataModel)
        // тут уже логика презентации экрана используя знание о self.vc
    }
}
```

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/MasterViewController.swift
> +    init(presenter:IMasterPresenter) {
Потерялся пробел

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/Views/CustomTableViewCell.swift
> +    func setupCell(heading:String, text:String, time:String) {
Потерялись пробелы

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/Views/MasterView.swift
> +    var didSelectRowAt:((Int) -> Void)? { get set }
Потерялся пробел

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/Views/MasterView.swift
> +    func setupDataModel(dataModel:[DataModel]) {
Потерялся пробел

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Master/Views/MasterView.swift
> +    }
В данном случае нам уже понадобился IndexPath (в прошлый раз я либо просмотрел, либо этого метода не было), по этому давай передавать сюда IndexPath, а не Int

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Model/CustomTableViewDataSource.swift
> +        else { assertionFailure(); return UITableViewCell()}
Лучше разнести все по разным строкам, сейчас это прям очень не очень читается

2020-11-26 21:40 UTC, korshunigor commented on Homework_№5/VIPER/Homework_№4/Model/CustomTableViewDelegate.swift
> +        static let tableViewEstimatedHeight:CGFloat = 44
Потерялся пробел

2020-11-27 04:23 UTC, Lumkooo commented on Homework_№5/VIPER/Homework_№4/Detail/DetailPresenter.swift
> +        self.interactor.presenter = self
Тогда я не совсем понимаю как мы его туда передадим,  ведь при создании Interactor-у надо будет знать о Presenter-е, а Presenter-у об Interactor-е, то есть:

        let interactor = MasterInteractor(presenter: <#IMasterInteractorOutput#>)
        let router = MasterRouter()
        let presenter = MasterPresenter(interactor: interactor, router: router)
        let masterController = MasterViewController(presenter: presenter)

2020-11-27 04:30 UTC, Lumkooo commented on Homework_№5/VIPER/Homework_№4/Master/MasterRouter.swift
> +    func showDetailViewController(on view: IMasterView, with dataModel: DataModel)
Здесь то же самое недопонимание, как и сверху, если мы сделаем такой init, то нам надо будет в роутер передать masterController, которого еще нет... Код из MasterAssembly: 

        let interactor = MasterInteractor()
        let router = MasterRouter(vc: UIViewController )
        let presenter = MasterPresenter(interactor: interactor, router: router)
        let masterController = MasterViewController(presenter: presenter)
        return masterController

Видимо туплю, потому что не понимаю как мы это сделаем, если для инициализации первого нам нужен второй и для инициализации второго нам нужен первый. А если передавать просто UIViewContorller(), то оно и не работает.

2020-11-27 04:35 UTC, Lumkooo commented
Перезалил CLEAN версию в проект, поправил замечания, кроме router-а и Interactor-а потому что не могу понять как мы передаем их друг-другу в инициализаторы( Если презентеру для инициализации нужен интерактор, а интерактору для инициализации нужен презентер)
Насчет пробелов - не знаю как так получается, раньше просто за этим не смотрел и потому, наверное, не замечаю. Но теперь стараюсь обращать на это больше внимания

2020-11-27 07:50 UTC, korshunigor commented
> поправил замечания, кроме router-а и Interactor-а потому что не могу понять как мы передаем их друг-другу в инициализаторы( Если презентеру для инициализации нужен интерактор, а интерактору для инициализации нужен презентер)

На счет передачи через инициализатор это была рекомендация на случай если нам ни чего не мешает так сделать. В случае же как описано в твоем сообщении (интерактору нужен презентер, а презентеру интерактор), ты можешь в одном случае передать через инициализатор (допустим интерактор в презентер), а во втором заметить свойство (допустим обратиться к `interactor.presenter = presenter`. Важный момент, в протокол мы все равно не включаем эти свойства, доступ к ним должен быть только если мы работаем с самим объектом (допустим с MasterInteractor) на этапе конфигурирования модуля в Assembly

2020-11-27 11:13 UTC, Lumkooo commented
Точно, спасибо большое, поправил 😊

2021-01-31 05:50 UTC, merged